"""Add new column in ShoppingCardDetailTable

Revision ID: aa92f1835be5
Revises: 501e08a0dce7
Create Date: 2025-02-17 03:39:09.806616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa92f1835be5'
down_revision = '501e08a0dce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_card_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_card_details', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
