"""Add delete colum

Revision ID: af7347d21564
Revises: a167e55eac7c
Create Date: 2025-02-16 04:00:53.256311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af7347d21564'
down_revision = 'a167e55eac7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subcategory', type_='foreignkey')
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_subcategory', 'subcategories', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###
