"""add subcategory_id in product table

Revision ID: e91a5fab66e5
Revises: aa92f1835be5
Create Date: 2025-02-18 05:34:51.092177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91a5fab66e5'
down_revision = 'aa92f1835be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###
